// lib/mockData.ts
import { Club } from './types';

export const mockClubs: Club[] = [
  {
    id: '1',
    name: 'École de Voile de Marseille',
    region: 'Provence-Alpes-Côte d\'Azur',
    department: '13',
    city: 'Marseille',
    address: '1 rue de la Plage, Vieux Port',
    zipCode: '13000',
    phone: '04 91 54 69 86',
    email: 'contact@voilemarseille.fr',
    website: 'www.voilemarseille.fr',
    googleMapsUrl: 'https://maps.google.com',
    description: 'École de voile complète avec dériveur, catamaran et planche à voile.',
    activities: ['Dériveur', 'Catamaran', 'Planche à voile'],
    ageRange: ['Enfants', 'Ados', 'Adultes'],
    scheduleOpen: 'Lun-Dim: 09:00-18:00',
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    name: 'Club Nautique de Cannes',
    region: 'Provence-Alpes-Côte d\'Azur',
    department: '06',
    city: 'Cannes',
    address: 'Port Pierre Canto',
    zipCode: '06400',
    phone: '04 93 47 27 70',
    email: 'info@clubnauti-cannes.fr',
    description: 'Voile légère et croisière en Méditerranée.',
    activities: ['Dériveur', 'Voilier'],
    ageRange: ['Ados', 'Adultes'],
    createdAt: new Date('2024-01-02'),
  },
  {
    id: '3',
    name: 'Ligue de Voile de Brest',
    region: 'Bretagne',
    department: '29',
    city: 'Brest',
    address: 'Port de Plaisance, Boulevard de la Liberté',
    zipCode: '29200',
    phone: '02 98 47 70 64',
    email: 'ligue@liguevoilebrest.fr',
    website: 'www.liguevoilebrest.fr',
    description: 'Ligue affiliée FFV - Courses et loisirs en baie de Brest.',
    activities: ['Dériveur', 'Catamaran', 'Voilier'],
    ageRange: ['Enfants', 'Ados', 'Adultes'],
    scheduleOpen: 'Mar-Dim: 10:00-17:00',
    createdAt: new Date('2024-01-03'),
  },
  {
    id: '4',
    name: 'Windsurf Club Cagliari',
    region: 'Corse',
    department: '20',
    city: 'Cagliari',
    address: 'Plage Poetto',
    zipCode: '09100',
    phone: '04 95 23 45 67',
    email: 'contact@windsurfcorse.com',
    activities: ['Planche à voile', 'Wingfoil'],
    ageRange: ['Ados', 'Adultes'],
    createdAt: new Date('2024-01-04'),
  },
  {
    id: '5',
    name: 'Voile Loisirs Nice',
    region: 'Provence-Alpes-Côte d\'Azur',
    department: '06',
    city: 'Nice',
    address: 'Port Lympia',
    zipCode: '06300',
    phone: '04 92 00 68 94',
    email: 'loisirs@voilenice.fr',
    description: 'Sorties découverte et slow tourisme en Méditerranée.',
    activities: ['Voilier'],
    ageRange: ['Enfants', 'Ados', 'Adultes'],
    createdAt: new Date('2024-01-05'),
  },
  {
    id: '6',
    name: 'École de Voile de Saint-Malo',
    region: 'Bretagne',
    department: '35',
    city: 'Saint-Malo',
    address: 'Plage de l\'Eventail',
    zipCode: '35400',
    phone: '02 99 40 44 00',
    email: 'contact@evstmalo.fr',
    activities: ['Dériveur', 'Catamaran', 'Planche à voile'],
    ageRange: ['Enfants', 'Ados', 'Adultes'],
    scheduleOpen: 'Lun-Dim: 08:00-19:00',
    createdAt: new Date('2024-01-06'),
  },
  {
    id: '7',
    name: 'Club Nautique Méditerranée',
    region: 'Provence-Alpes-Côte d\'Azur',
    department: '83',
    city: 'Toulon',
    address: 'Port de Toulon',
    zipCode: '83000',
    phone: '04 94 92 84 85',
    email: 'nautique.med@gmail.com',
    activities: ['Voilier', 'Catamaran', 'Dériveur'],
    ageRange: ['Adultes'],
    createdAt: new Date('2024-01-07'),
  },
  {
    id: '8',
    name: 'Voile Vannes',
    region: 'Bretagne',
    department: '56',
    city: 'Vannes',
    address: 'Golfe du Morbihan',
    zipCode: '56000',
    phone: '02 97 47 61 23',
    email: 'contact@sailvannes.fr',
    activities: ['Dériveur', 'Catamaran'],
    ageRange: ['Enfants', 'Ados', 'Adultes'],
    createdAt: new Date('2024-01-08'),
  },
  {
    id: '9',
    name: 'Surf & Voile Antibes',
    region: 'Provence-Alpes-Côte d\'Azur',
    department: '06',
    city: 'Antibes',
    address: 'Port Vauban',
    zipCode: '06600',
    phone: '04 93 34 52 00',
    email: 'contact@surfvoileantibes.fr',
    website: 'www.surfvoileantibes.fr',
    description: 'Glisse et voile légère, stages d\'été.',
    activities: ['Planche à voile', 'Wingfoil', 'Stand-up paddle'],
    ageRange: ['Ados', 'Adultes'],
    createdAt: new Date('2024-01-09'),
  },
  {
    id: '10',
    name: 'Ligue de Voile de Belle-Île',
    region: 'Bretagne',
    department: '56',
    city: 'Belle-Île-en-Mer',
    address: 'Port de Sauzon',
    zipCode: '56360',
    phone: '02 97 31 81 93',
    email: 'ligue@belleilevoile.fr',
    activities: ['Dériveur', 'Catamaran', 'Voilier'],
    ageRange: ['Enfants', 'Ados', 'Adultes'],
    createdAt: new Date('2024-01-10'),
  },
];

// Données pour les filtres
export const regions = [
  'Provence-Alpes-Côte d\'Azur',
  'Bretagne',
  'Corse',
  'Normandie',
  'Pays de la Loire',
  'Nouvelle-Aquitaine',
];

export const activities = [
  'Dériveur',
  'Catamaran',
  'Voilier',
  'Planche à voile',
  'Wingfoil',
  'Stand-up paddle',
  'Voilier habitable',
  'Croisière',
];
